### ISSUE TITLE
multivariate penguin vignettes

### ISSUE THREAD

**Issue by friendly** [allisonhorst/palmerpenguins#35]
Hi
I completed another vignette, published on Rpubs

Can you please edit the `vignettes/articles/user_contributions.Rmd` file to include these links

### Links to user-contributed examples, posts and vignettes: 

* [Penguins data: Multivariate EDA](https://rpubs.com/friendly/penguin-biplots)
    + Author: Michael Friendly
    + Description: These examples show the use of multivariate exploratory visualization methods -- principal component analysis and biplots -- to understand the relations among variables in the penguins data set.

* [Penguins data: MANOVA and HE plots](https://rpubs.com/friendly/penguin-manova)
    + Author: Michael Friendly
    + Description: This vignette illustrates the use of MANOVA, HE plots and canonical discriminant analysis in the analysis of the Palmer penguins data.

**Comment by allisonhorst** [comment]
Both examples are added to [user contributed examples](https://github.com/allisonhorst/palmerpenguins/blob/master/vignettes/user_contributions.Rmd). Thanks!
