### ISSUE TITLE
Julia package

### ISSUE THREAD

**Issue by devmotion** [allisonhorst/palmerpenguins#44]
Hej!

First of all, I'd like to thank you for providing the Palmer penguins dataset and the accompanying resources! I want to inform you that I put together a [Julia package "PalmerPenguins.jl"](https://github.com/devmotion/PalmerPenguins.jl) to make the dataset more easily accessible for Julia users and developers. The package uses [DataDeps.jl](https://github.com/oxinabox/DataDeps.jl) to download the CSV file of the dataset once and to make it available for further use. Users are presented with a summary of the information in https://github.com/allisonhorst/palmerpenguins/blob/master/README.md such as authors, website, general structure, license, and how to cite the dataset (the same information is also included in https://github.com/devmotion/PalmerPenguins.jl/blob/master/README.md).

I hope I gave credit to your work correctly - in particular I'm wondering if it's OK to use the logo (IMO it looks really great) to link to your webpage?

**Comment by allisonhorst** [comment]
That is great, we're thrilled to see the penguins easier to access in other languages! The citation looks good and you're welcome to use the palmerpenguins logo. We appreciate you checking with us!

Also just a heads up: we may be updating the location of the penguins.csv in our repo, & will reach out to you if/when we do so that you can update it in your Julia package so it doesn't break.

**Comment by devmotion** [comment]
Great, sounds good! I'll update the location if/when it's needed :+1:

**Comment by allisonhorst** [comment]
OK, the CSVs (penguins.csv and penguins_raw.csv) are now here: https://github.com/allisonhorst/palmerpenguins/tree/master/inst/extdata

Thank you for updating in PalmerPenguins.jl! 

-Allison

**Comment by devmotion** [comment]
Thanks, I updated the Julia package! BTW for reproducibility the download links in the Julia package are pointing to specific commits (see https://github.com/devmotion/PalmerPenguins.jl/blob/1fac8313ef0cb14200bc6554d91d229a9462ead7/src/PalmerPenguins.jl#L7), and hence the package doesn't break even if the location of the CSV files is updated (well, as long as you don't erase the git history or move away from Github, I guess). It's nice that it's possible to provide the raw data in an easy way as well now!
