### ISSUE TITLE
Match culmen_depth.png to new column names

### ISSUE THREAD

**Issue by karaesmen** [allisonhorst/palmerpenguins#52]
Hi!

Thanks so much for all your effort in this package and the beautiful illustrations! 👩‍🎨 💕

I would love to be able to use the **culmen_depth.png** for a tutorial I am building. 
Since the column names have been changed from `culmen_*` to to `bill_*`, I was wondering if you could update culmen depth  illustration to reflect that when you get a chance? 🐧  

Thank you!

**Comment by allisonhorst** [comment]
We agree! We'll update throughout. In the meantime, here you go: 
![penguin_bills](https://user-images.githubusercontent.com/25372780/87191569-8b446b80-c2a9-11ea-95a1-8319d2d30264.png)

**Comment by karaesmen** [comment]
Wonderfull!!🎉 
Thanks so much for the quick reply!!

**Comment by allisonhorst** [comment]
Updated to new bill length / depth illustration throughout.
