### ISSUE TITLE
User-contributed examples

### ISSUE THREAD

**Issue by jhk0530** [allisonhorst/palmerpenguins#54]
Hi, thanks for great data. I love penguins :)

I made short data analysis example, which is published to [R-bloggers](https://www.r-bloggers.com/basic-data-analysis-with-palmerpenguins/).

and if you allow, I hope for using that post as [User-contributed examples](https://allisonhorst.github.io/palmerpenguins/articles/user_contributions.html)

Please let me know, if there's any issue or instruction about these process.

Thanks.

**Comment by allisonhorst** [comment]
You example is added to [user-contributed examples](https://github.com/allisonhorst/palmerpenguins/blob/master/vignettes/user_contributions.Rmd). Thank you!
