### ISSUE TITLE
Update pkgdown GHA workflow

### ISSUE THREAD

**Issue by jennybc** [allisonhorst/palmerpenguins#92]
I'm about to TA in a workshop that Hadley is teaching and we're going to use palmerpenguins. So I installed it and noticed it was very recently updated and binaries aren't available yet, so I just wanted to check on what the changes were. And I saw some recent changes to the pkgdown workflow.

It turns out it's much better to update the entire workflow file. It doesn't really work so well to just edit `v1` to `v2`, for example.

https://www.tidyverse.org/blog/2022/06/actions-2-0-0/#simpler-workflow-files

I don't know if you're currently having any problems because of this, but it's just a good idea to freshen the whole workflow. I'll make a PR and you can see what you think. If you're worried about merging it, I'll also stick around long enough to work through any issues.

**Comment by apreshill** [comment]
Thank you @jennybc - PR very much appreciated! We were flailing to fix the CRAN HTML warnings as quickly as possible 😩

**Comment by apreshill** [comment]
Here were the warnings that we were sent: https://cran.r-project.org/web/checks/check_results_palmerpenguins.html

**Comment by jennybc** [comment]
Yeah your pkgdown site is really a completely separate matter. In fact, I don't quite understand why CRAN shows no vignettes for palmerpenguins.

https://cran.r-project.org/web/packages/palmerpenguins/index.html

Do you submit something other than the source I see here? I ask because I was looking at the extra packages being installed for the pkgdown site and was trying to achieve same through more official means. And I wondered why the use of the here package wasn't already causing problems on CRAN, since it's not listed in DESCRIPTION. In any case, if there's any need to rationalize something, I'm happy to help.
